#!/usr/bin/python3.7
# -*- coding: utf-8 -*-
# @Time    : 2021/4/30 19:56 
# @Author  : ana
# @File    : Collection7_supporting.py
# @Software: PyCharm

class Collection7Supporting:
    startUrl = ["http://www.bmnh.org.cn/gzxx/gzbb/1/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/1/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/1/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/1/list_4.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/1/list_5.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/1/list_6.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/2/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/2/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/2/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/2/list_4.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/2/list_5.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/2/list_6.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/3/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/3/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/3/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/4/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/4/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/4/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/4/list_4.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/4/list_5.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/4/list_6.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/5/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/5/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/8/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/8/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/8/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/8/list_4.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/9/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/10/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/10/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/11/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/11/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/11/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/11/list_4.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/11/list_5.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/11/list_6.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/12/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/12/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/12/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/12/list_4.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/12/list_5.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/13/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/13/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/13/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/13/list_4.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/14/list.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/14/list_2.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/14/list_3.shtml",
                "http://www.bmnh.org.cn/gzxx/gzbb/14/list_4.shtml",
                ]
